BANPars/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog
from django.utils.translation import gettext_lazy as _


admin.site.index_title = _('Admin Panel')
admin.site.site_header = _('Company Admin Panel')
admin.site.site_title = _('Company')


urlpatterns = [
    path('lang/', include('lang_ctrl.urls', namespace='lang')),
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('introduction.urls', namespace='introduction')),
    path('shop/', include('store.urls', namespace='store')),
    path('account/', include('accounts.urls', namespace='accounts')),  
    path('basket/', include('basket.urls', namespace='basket')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('addresses/', include('addresses.urls', namespace='addresses')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('preorder/', include('preorder.urls', namespace='preorder')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='js-cat'),
)


accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.accounts_register, name='register'),
    path('verify/', views.verify_account, name='verify'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('password_reset/', views.forgotten_password, name='forgetPass'),
    path('password_reset/<token>/', views.change_forgotten_password, name='change_forgotten_password'),
    path('edit/', views.profileEdit, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'), 
]

basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

introduction/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from django.conf import settings

from . import views


app_name = 'introduction'


urlpatterns = [
    # path('', cache_page(settings.CACHE_TTL)(views.intro), name='company'),
    path('', views.intro, name='company'),
    path('contact/', views.contact, name='contact'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
    path('feature/<pk>/', views.toggle_feature, name='feature_price'),
    path('option/<pk>/', views.toggle_option, name='option_price'),
]

templates/base/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!doctype html>
<html lang="en">
<head>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon/favicon.ico' %}"/>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- BOOTSTRAP AND FONTAWESOME -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- END OF BOOTSTRAP AND FONTAWESOME -->


    <!-- CSS FILES LINKS -->
    <link rel="stylesheet" href="{% static 'css/base/main.css' %}">
    {% if LANGUAGE_CODE == 'en' %}
        <link rel="stylesheet" href="{% static 'css/base/lang/en-main.css' %}">
    {% endif %}

    {% if LANGUAGE_CODE == 'fa' %}
        <link rel="stylesheet" href="{% static 'css/base/lang/fa-main.css' %}">
    {% endif %}

    {% if LANGUAGE_CODE == 'ar' %}
        <link rel="stylesheet" href="{% static 'css/base/lang/ar-main.css' %}">
    {% endif %}
    <!-- END OF CSS FILES LINKS -->


    {% block links %}
    {% endblock %}
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>

    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    {% block js-files %}
    {% endblock %}

</body>
</html>

templates/base/footer.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}


<!-- CSS FILES LINKS -->
<link rel="stylesheet" href="{% static 'css/footer/footer.css' %}">

{% if LANGUAGE_CODE == 'en' %}
    <link rel="stylesheet" href="{% static 'css/footer/lang/en-footer.css' %}">
{% endif %}

{% if LANGUAGE_CODE == 'fa' %}
    <link rel="stylesheet" href="{% static 'css/footer/lang/fa-footer.css' %}">
{% endif %}

{% if LANGUAGE_CODE == 'ar' %}
    <link rel="stylesheet" href="{% static 'css/footer/lang/ar-footer.css' %}">
{% endif %}
<!-- END OF CSS FILE LINKS -->




<section class="section footer" id="footer">
    <div class="section-center footer-center">
        <div class="footer-col">
            <img src="{% static 'images/introduction/logo.png' %}" alt="The Company Logo" class="footer-logo">
            <p>{% translate 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum porro, quia voluptatem pariatur nihil molestiae pe' %}</p>
        </div>

        <div class="footer-col">
            <h4>{% translate 'features' %}</h4>
            <p>{% translate 'deals & offers' %}</p>
            <p>{% translate 'customer reviews' %}</p>
            <p>{% translate 'cancelations policy' %}</p>
        </div>

        <div class="footer-col">
            <h4>{% translate 'quick contact' %}</h4>
            <p><span><i class="fas fa-phone"></i></span>+091458721459</p>
            <p><span><i class="fas fa-envelope"></i></span>contact@website.com</p>
            <p><span><i class="fas fa-home"></i></span>{% translate 'XYZ road, XYZ complex' %}</p>
        </div>

        <div class="footer-col">
            <h4>{% translate 'follow us on' %}</h4>
            <p><a href="#"><i class="fab fa-instagram"></i></a>{% translate 'instagram' %}</p>
            <p><a href="#"><i class="fab fa-youtube"></i></a>{% translate 'youtube' %}</p>
            <p><a href="#"><i class="fab fa-twitter"></i></a>{% translate 'twitter' %}</p>
        </div>

    </div>
    <div class="footer-divider"></div>
    <div class="copyright">
        <p>{% translate 'copyright &copy; company | all rights reserved' %}</p>
    </div>
</section>

templates/base/main-navbar.html
{% load static %}
{% load i18n %}
{% load cache %}
{% get_current_language as LANGUAGE_CODE %}
{% load lang_switcher %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/nav/main-navbar.css' %}">

    <!-- Add transparency for the navbar only for home page -->
    {% with "/"|add:LANGUAGE_CODE|add:"/" as address %}
        {% if request.get_full_path == address %}
        <link rel="stylesheet" href="{% static 'css/nav/transparent-navbar.css' %}">
        {% endif %}
    {% endwith %}
{% endblock %}


<nav class="nav" id="nav">
    <div class="nav-center">
        <div class="nav-header">
            {% cache cache_ttl logo %}
            <img src="{% static 'images/introduction/logo.png' %}" class="nav-logo" alt="nav logo" />
            {% endcache logo %}
            <div class="lang-dropdown  dropdown">
                <button class="dropbtn"> <span id="selected-lang">en</span> <span><i class="fas fa-angle-down"></i></span> </button>
                <div class="dropdown-content lang-content">
                    <a id="lang-en" href="{{ request|switch_lang:'en' }}">{% translate 'EN' %}</a>
                    <a id="lang-fa" href="{{ request|switch_lang:'fa' }}">{% translate 'FA' %}</a>
                    <a id="lang-ar" href="{{ request|switch_lang:'ar' }}">{% translate 'AR' %}</a>
                </div>
            </div>
            <button class="nav-btn" id="nav-btn">
                <i class="fas fa-bars"></i>
            </button>
        </div>
        <div class="nav-link-container">
            <ul class="nav-links">
                <li>
                    <a href="{% url 'introduction:company' %}">{% translate 'home' %}</a>
                </li>
                <li>
                    <!-- <a href="{% url 'store:product_all' %}">{% translate 'shop' %}</a> -->
                    <a href="{% url 'store:product_all' %}">{% translate 'products' %}</a>
                </li>
                <li>
                    <a href="#">{% translate 'solutions' %}</a>
                </li>
                <li>
                    <a href="#">{% translate 'about' %}</a>
                </li>
                <li>
                    <a href="{% url 'introduction:contact' %}">{% translate 'contact' %}</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="dropdown">
                        <img src="{{avatar.url}}" class="profile-picture dropbtn">
                        <!-- <button class="dropbtn">Dropdown</button> -->
                        <div class="dropdown-content">
                            <a href="{% url 'accounts:edit_profile' %}">{% translate 'profile' %}</a>
                            <a type="button" role="button" href="{% url "basket:basket_summary" %}"
                                class="">

                                {% with total_qty=basket|length %}
                                    <div id="basket-qty" class="d-inline-flex">
                                        {% if total_qty > 0 %}
                                            {{ total_qty }}
                                        {% else %}
                                            0
                                        {% endif %}
                                    </div>
                                {% endwith %} 

                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                    class="bi bi-cart3" viewBox="0 0 16 16">
                                    <path
                                        d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                                </svg>
                                {% translate 'cart' %}
                            </a>
                            <a href="{% url 'accounts:logout' %}">{% translate 'logout' %}</a>
                        </div>
                    </li>

                    <li class="nav-mobile-links">
                        <a href="{% url 'accounts:edit_profile' %}">{% translate 'profile' %}</a>
                    </li>
                    <li class="nav-mobile-links">
                        <a type="button" role="button" href="{% url "basket:basket_summary" %}"
                                class="">

                                {% with total_qty=basket|length %}
                                    <div id="basket-qty" class="d-inline-flex">
                                        {% if total_qty > 0 %}
                                            {{ total_qty }}
                                        {% else %}
                                            0
                                        {% endif %}
                                    </div>
                                {% endwith %} 

                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                    class="bi bi-cart3" viewBox="0 0 16 16">
                                    <path
                                        d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                                </svg>
                                {% translate 'cart' %}
                            </a>
                    </li>
                    <li class="nav-mobile-links">
                        <a href="{% url 'accounts:logout' %}">{% translate 'logout' %}</a>
                    </li>
                    <li class="nav-mobile-links">
                        <a id="lang-en" href="{{ request|switch_lang:'en' }}">{% translate 'EN' %}</a>
                        <a id="lang-fa" href="{{ request|switch_lang:'fa' }}">{% translate 'FA' %}</a>
                        <a id="lang-ar" href="{{ request|switch_lang:'ar' }}">{% translate 'AR' %}</a>
                    </li>
                {% else %}
                <li class="btn">
                    <a href="{% url 'accounts:login' %}">{% translate 'login' %}</a>
                </li>
                <li class="nav-mobile-links">
                    <a id="lang-en" href="{{ request|switch_lang:'en' }}">{% translate 'EN' %}</a>
                    <a id="lang-fa" href="{{ request|switch_lang:'fa' }}">{% translate 'FA' %}</a>
                    <a id="lang-ar" href="{{ request|switch_lang:'ar' }}">{% translate 'AR' %}</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>




<!-- language control -->
<script>
    const language = '{{ LANGUAGE_CODE }}';
    const langLink = document.getElementById(`lang-${language}`);
    const currentLang = document.getElementById('selected-lang');
    currentLang.innerText = langLink.innerText.toLowerCase();

    // on <768px pages
    const lang_links = document.querySelectorAll(".nav-mobile-links:nth-last-of-type(1)")[0].querySelectorAll('a');
    lang_links.forEach(l => {
        if (l.id === `lang-${language}`) {
            l.classList.add('active-lang');
        }
    })
</script>


<!-- nav toggle -->
<script>
// select button and links
const navBtn = document.getElementById("nav-btn");
const links = document.querySelector(".nav-link-container");
// add event listener
navBtn.addEventListener("click", () => {
    links.classList.toggle("show-links");
});
</script>