BANPars/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog
from django.utils.translation import gettext_lazy as _


admin.site.index_title = _('Admin Panel')
admin.site.site_header = _('Company Admin Panel')
admin.site.site_title = _('Company')


urlpatterns = [
    path('lang/', include('lang_ctrl.urls', namespace='lang')),
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('introduction.urls', namespace='introduction')),
    path('shop/', include('store.urls', namespace='store')),
    path('account/', include('accounts.urls', namespace='accounts')),  
    path('basket/', include('basket.urls', namespace='basket')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('addresses/', include('addresses.urls', namespace='addresses')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('preorder/', include('preorder.urls', namespace='preorder')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='js-cat'),
)


accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.accounts_register, name='register'),
    path('verify/', views.verify_account, name='verify'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('password_reset/', views.forgotten_password, name='forgetPass'),
    path('password_reset/<token>/', views.change_forgotten_password, name='change_forgotten_password'),
    path('edit/', views.profileEdit, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'), 
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
    path('feature/<pk>/', views.toggle_feature, name='feature_price'),
    path('option/<pk>/', views.toggle_option, name='option_price'),
]

accounts/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from customUser.models import User
from .models_utils import profile_directory_path

from django.utils import timezone

## Created and Updated missing !!!!
class Profile (models.Model) :
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', verbose_name=_('User'))

    avatar = models.ImageField(upload_to=profile_directory_path, default='profiles/no_profile.png',
                                                                verbose_name=_('Profile Picture'))
    bio = models.TextField(max_length=500, blank=True, verbose_name=_('Biography'))
    company = models.TextField(max_length=500, blank=True, verbose_name=_('Company'))
    website = models.URLField(max_length=200, blank=True, verbose_name=_('Company website'))

    created = models.DateTimeField(auto_now_add=True, verbose_name=_('Created at'))
    updated = models.DateTimeField(auto_now=True, verbose_name=_('Updated at'))

    class Meta :
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')

    # def filename(self):
    #     return os.path.basename(self.avatar.name)

    def __str__(self):
        return _('Profile of {}').format(self.user.username)

accounts/forms.py
from django import forms
from django.conf import settings
from django.core.files.images import get_image_dimensions
from django.utils.translation import gettext_lazy as _

from customUser.models import User
from .models import Profile

from BANPars.redis_conf import redis

from persian_tools import phone_number
from BANPars.settings import OTP_LENGTH


def has_numbers_and_alphabet(inputString):
    a = any(char.isdigit() for char in inputString)
    b = any(char.isalpha() for char in inputString)
    return (a and b)


class RegistrationForm(forms.Form) :
    username = forms.CharField(label=_('Phone Number'), max_length=11, help_text=_('Required'),
                                error_messages={'required' : _('Phonenumber can not be blank'),
                                                            'invalid': _('Invalid phonenumber')})

    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password1 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    def clean_username(self) :
        username = self.cleaned_data['username']

        if not phone_number.validate(username) :
            raise forms.ValidationError('Phonenumber is not valid')

        r = User.objects.filter(username=username)
        if r.count() :
            raise forms.ValidationError('Username already exists')

        return username

    # Password circumastances = at least 5 char long, including digits and alphabets
    def clean_password1(self) :
        password = self.cleaned_data['password']
        if len(password) < 5 :
            raise forms.ValidationError('Password must be at least 5 characters long')
        if not has_numbers_and_alphabet(password) :
            raise forms.ValidationError('Password must contain digits and alphabets')

        cd = self.cleaned_data
        if cd['password'] != cd['password1'] :
            raise forms.ValidationError('Passwords do not match !!!')

        return cd['password1']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'placeholder': _('Username'), })
        self.fields['password'].widget.attrs.update(
            {'placeholder': _('Password'), })
        self.fields['password1'].widget.attrs.update(
            {'placeholder': _('Repeat Password'), })

class VerificationForm(forms.Form) :
    number = forms.CharField(label=_('Phone Number'), max_length=11, help_text=_('Required'),
                            error_messages={'required' : _('Phonenumber can not be blank'),
                                'invalid': _('Invalid Phonenumber')})

    otp = forms.CharField(label=_('Verification Code'), help_text=_('Required'),
                            error_messages={'required' : _('OTP can not be blank'),
                                'invalid': _('Invalid OTP')})

    def clean_number(self) :
        number = self.cleaned_data['number']
        if not phone_number.validate(number) :
            raise forms.ValidationError(_('Wrong Phonenumber'))
        return number

    def clean_otp(self) :
        number = self.cleaned_data['number']
        otp = self.cleaned_data['otp']
        try :
            predefined_otp = redis.get(str(number)).decode('utf-8')
        except :
            raise forms.ValidationError(_('Verification code is expired, press resend'))

        if not otp == predefined_otp :
            raise forms.ValidationError(_('Wrong code, try again'))
        else :
            return otp

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['number'].widget.attrs.update(
            {'placeholder': _('Phone Number'), })
        self.fields['otp'].widget.attrs.update(
            {'placeholder': _('Verification Code'), })

class UserLoginForm(forms.Form) :
    username = forms.CharField(label=_('Username'),
                                help_text=_('Required'),
                                error_messages={'invalid' : _('Username must contain at least 5 characters'), })
    password = forms.CharField(label=_('Password'), widget=forms.PasswordInput)

    def clean_username(self) :
        username = self.cleaned_data['username'].lower()
        try :
            r = User.objects.get(username=username)
        except :
            r = None
        if not r :
            raise forms.ValidationError(_('Wrong crendtials'))
        return username

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'placeholder': _('Username'), })
        self.fields['password'].widget.attrs.update(
            {'placeholder': _('Password'), })

class SetNewPasswordForm(forms.Form) :
    password = forms.CharField(label=_('New Password'), widget=forms.PasswordInput)
    password1 = forms.CharField(label=_('Repeat Password'), widget=forms.PasswordInput)

    def clean_password1(self) :
        cd = self.cleaned_data
        if cd['password'] != cd['password1'] :
            raise forms.ValidationError('Passwords do not match !!!')
        password = self.cleaned_data['password']
        if len(password) < 5 :
            raise forms.ValidationError('Password must be at least 5 characters long')
        if not has_numbers_and_alphabet(password) :
            raise forms.ValidationError('Password must contain digits and alphabets')
        return cd['password1']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget.attrs.update({'placeholder': _('New Password'), })
        self.fields['password1'].widget.attrs.update({'placeholder': _('Repeat New Password'), })

class UserEditForm (forms.ModelForm) :
    fullname = forms.CharField(label=_('Fullname'), max_length=100)

    email = forms.EmailField(label=_('Email Address'))

    class Meta :
        model = User
        fields = ('fullname', 'email', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['fullname'].required = False
        self.fields['fullname'].widget.attrs.update({'placeholder': _('Fullname'), })
        self.fields['email'].required = False
        self.fields['email'].widget.attrs.update({'placeholder': _('Email'), })

class ProfileDataForm (forms.ModelForm) :

    class Meta :
        model = Profile
        fields = ('bio', 'company', 'website', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['bio'].required = False
        self.fields['company'].required = False
        self.fields['website'].required = False

        self.fields['bio'].widget.attrs.update({'placeholder': _('Tell us a bit about yourself'), 'rows' : 5})
        self.fields['company'].widget.attrs.update({'placeholder': _('Company'), 'rows' : 3})
        self.fields['website'].widget.attrs.update({'placeholder': _('Company website'), })

class ProfileAvatarForm (forms.ModelForm) :
    avatar = forms.ImageField(label=_('Profile Picture'), error_messages = {'invalid':_("Image files only")}, widget=forms.FileInput)

    class Meta :
        model = Profile
        fields = ('avatar',)

    def clean_avatar (self) :
        picture = self.cleaned_data['avatar']
        if not picture:
            raise forms.ValidationError(_("No image!"))

        w, h = get_image_dimensions(picture)
        if w > settings.PROFILE_WIDTH or h > settings.PROFILE_HEIGHT:
            raise forms.ValidationError(_('Width and height of the image is more than {}').format(settings.PROFILE_WIDTH))

        if picture.size > settings.PROFILE_MAX_SIZE :
            raise forms.ValidationError(_('Profile image can not be over {} mb').format(settings.PROFILE_MAX_SIZE/1024/1024))

        return picture

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['avatar'].required = False

class ChangePassword(SetNewPasswordForm) :
    old_password = forms.CharField(label=_('Old Password'), widget=forms.PasswordInput)

    field_order = ('old_password', 'password', 'password1', )

    def clean_old_password(self) :
        password = self.cleaned_data['old_password']
        if not self.related_user.check_password(password):
            raise forms.ValidationError(_('Invalid password'))

    def __init__(self, user, *args,**kwargs):
        self.related_user = user
        super().__init__(*args,**kwargs)
        self.fields['old_password'].widget.attrs.update({'placeholder': _('old password'), })
        self.fields['password'].widget.attrs.update({'placeholder': _('password'), })
        self.fields['password1'].widget.attrs.update({'placeholder': _('new password'), })

templates/accounts/base_profile.html
{% extends "base/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% load i18n %}

{% block content %}
{% include "base/main-navbar.html" %}


<div class="section profile-container">
    <div class="section-center row">
        <div class="col-md-4 sidebar-container">
            <div class="card sidebar">

                <div class="card-body">
                    {% if avatar %}
                    <img src="{{ avatar.url }}" class="rounded-circle">
                    {% endif %}
                    <div class="mt-3">
                        <ul>
                            <li><a href="{% url 'accounts:edit_profile' %}">{% translate 'Profile' %}</a></li>
                            <li><a href="#">{% translate 'Orders' %}</a></li>
                            <li><a href="{% url 'accounts:change_password' %}">{% translate 'Change Password' %}</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8 profile-forms">
            {% block profile-form %}
            {% endblock %}
        </div>
    </div>
</div>


{% include 'base/footer.html' %}

<script>
    const sideBarLinks = document.querySelectorAll('.sidebar ul li a');
    const currentHref = window.location.href;


    // Taking care of active sidebar link
    window.addEventListener('DOMContentLoaded', e => {
        activateSidebarLink();

    })
    function activateSidebarLink() {
        sideBarLinks.forEach(link => {
            if (link.href === currentHref) {
                link.classList.add('active');
            }
        })
    }

</script>

{% endblock %}

templates/accounts/change_password.html
{% extends "accounts/base_profile.html" %}
{% load static %}
{% load widget_tweaks %}

{% load i18n %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/accounts/base_profile.css' %}">
<link rel="stylesheet" href="{% static 'css/accounts/edit_profile.css' %}">
{% endblock %}


{% block title %}{% translate 'Edit your account' %}{% endblock %}


{% block profile-form %}
<p class="h4 mb-4 font-weight-bold">{% translate 'Change Password' %}</p>
<hr>
<div class="row">

    <div class="col-md-8">
        <form method="POST">

            {% if form.errors %}
                {% for field in form %}
                    {% if field.errors %}
                        <div class="alert alert-error" role="alert">
                            {{ field.errors|striptags }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}

            {% csrf_token %}

            <div class="form-group">
                <label for="id_old_password">{% translate 'Old Password' %}</label>
                {{ form.old_password|attr:'class:form-control light-bg' }}
            </div>

            <div class="form-group">
                <label for="id_password">{% translate 'New Password' %}</label>
                {{ form.password|attr:'aria-describedby:passwordHelp'|attr:'class:form-control light-bg' }}
                <small id="passwordHelp" class="form-text text-muted">{% translate 'Password must be at least 5 characters long.' %}</small>
                <small id="passwordHelp" class="form-text text-muted">{% translate 'Password must contain numbers and alphebet.' %}</small>
            </div>

            <div class="form-group">
                <label for="id_password1">{% translate 'Repeat Password' %}</label>
                {{ form.password1|attr:'class:form-control light-bg' }}
            </div>

            <button class="btn" type="submit"
                value="Save changes" name='data-submit'>{% translate 'Update Password' %}</button>
        </form>
    </div>
</div>
{% endblock %}

templates/accounts/edit_profile.html
{% extends "accounts/base_profile.html" %}
{% load static %}
{% load widget_tweaks %}

{% load i18n %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/accounts/base_profile.css' %}">
<link rel="stylesheet" href="{% static 'css/accounts/edit_profile.css' %}">
{% endblock %}


{% block title %}{% translate 'Edit your account' %}{% endblock %}


{% block profile-form %}
<p class="h4 mb-4 font-weight-bold">{% translate 'Profile' %}</p>
<hr>
<div class="row">

    <div class="col-md-8">
        <form method="POST" enctype="multipart/form-data">

            {% if user_form.errors %}
            <div class="alert alert-error" role="alert">
                {% translate 'Error: Please try again!' %}
            </div>
            {% endif %}

            {% if profile_form.errors %}
                {% for field in profile_form %}
                    {% if field.errors %}
                        <div class="alert alert-error" role="alert">
                            {{ field.errors|striptags }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}

            {% csrf_token %}

            <div class="form-group">
                <label for="id_fullname">{% translate 'Name' %}</label>
                {{ user_form.fullname|attr:'aria-describedby:nameHelp'|attr:'class:form-control light-bg' }}
                <small id="nameHelp" class="form-text text-muted">{% translate 'Tell us your name so we get to khow you better.' %}</small>
            </div>

            <div class="form-group">
                <label for="id_email">{% translate 'Email address' %}</label>
                {{ user_form.email|attr:'aria-describedby:emailHelp'|attr:'class:form-control light-bg' }}
                <small id="emailHelp" class="form-text text-muted">{% translate 'We will share the latest news of our company with you.' %}</small>
            </div>

            <div class="form-group">
                <label for="id_bio">{% translate 'Bio' %}</label>
                {{ profile_data_form.bio|attr:'class:form-control light-bg' }}
            </div>

            <div class="form-group">
                <label for="id_company">{% translate 'Company' %}</label>
                {{ profile_data_form.company|attr:'aria-describedby:companyHelp'|attr:'class:form-control light-bg' }}
                <small id="companyHelp" class="form-text text-muted">{% translate 'We would like to khow much more about you, if you are a company.' %}</small>
            </div>

            <div class="form-group">
                <label for="id_website">{% translate 'Website' %}</label>
                {{ profile_data_form.website|attr:'class:form-control light-bg' }}
            </div>

            <button class="btn" type="submit"
                value="Save changes" name='data-submit'>{% translate 'Update Changes' %}</button>
        </form>
    </div>

    <div class="col-md-4">
        <form method="POST" enctype="multipart/form-data" id="avatar-form">
            <label class="font-weight-bold">{{ profile_avatar_form.avatar.label}}</label>

            {% if profile_avatar_form.errors %}
                {% for field in profile_avatar_form %}
                    {% if field.errors %}
                        <div class="alert alert-error" role="alert">
                            {{ field.errors|striptags }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}


            {% csrf_token %}
            {% if avatar %}
            <div class="my-2 dropdown">
                <img src="{{ avatar.url }}">
                <button class="btn dropbtn" type="button"><i class="fas fa-pencil-alt"></i>{% translate 'edit' %}</button>
                <div class="avatar-content">
                    <label for="id_avatar">
                        <div>{% translate 'Update photo' %}</div>
                        {{ profile_avatar_form.avatar}}
                    </label>
                    <input type="submit" name="delete-submit" value="Remove photo">
                    <input type="submit" name="image-submit" value="update-photo" id="avatar-submit">
                </div>
            </div>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

{% block js-files %}
<script>
    const avatarDropdownBtn = document.getElementById('avatar-form').querySelector('.dropbtn');
    const avatarContent = document.getElementById('avatar-form').querySelector('.avatar-content');
    const avatarChange = document.getElementById('id_avatar');

    // Taking care of file input on change submit
    avatarChange.addEventListener('change', e => {
        document.getElementById('avatar-submit').click();
    })
    
    // Taking care of avatar dropdown
    avatarDropdownBtn.addEventListener('click', e => {
        e.preventDefault();
        avatarContent.style.display = 'block';
    })
    window.addEventListener('click', e => {
        if (e.target.classList.contains('dropbtn') | e.target.parentElement.classList.contains('dropbtn')) {
            return;
        }
        if (avatarContent.style.display === 'block') {
            avatarContent.style.display = 'none';
        } else {
            return;
        }
    })
</script>
{% endblock %}