BANPars/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog
from django.utils.translation import gettext_lazy as _


admin.site.index_title = _('Admin Panel')
admin.site.site_header = _('Company Admin Panel')
admin.site.site_title = _('Company')


urlpatterns = [
    path('lang/', include('lang_ctrl.urls', namespace='lang')),
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('introduction.urls', namespace='introduction')),
    path('shop/', include('store.urls', namespace='store')),
    path('account/', include('accounts.urls', namespace='accounts')),  
    path('basket/', include('basket.urls', namespace='basket')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('addresses/', include('addresses.urls', namespace='addresses')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('preorder/', include('preorder.urls', namespace='preorder')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='js-cat'),
)


basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
    path('feature/<pk>/', views.toggle_feature, name='feature_price'),
    path('option/<pk>/', views.toggle_option, name='option_price'),
]

orders/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from customUser.models import User
from store.models import Product, Feature, Option
from addresses.models import Province, City



class Order (models.Model):
    user         = models.ForeignKey(User, on_delete=models.CASCADE,
                    related_name='orders', verbose_name=_('User'))
    fullname     = models.CharField(max_length=50, verbose_name=_('Fullname'))
    address      = models.TextField(max_length=500, verbose_name=_('Address'))
    delivery_instructions  = models.TextField(max_length=500,
                            verbose_name=_('Delivery instructions'), blank=True, default='')

    province = models.ForeignKey(Province, on_delete=models.PROTECT, verbose_name=_('Province'))
    city         = models.ForeignKey(City, on_delete=models.PROTECT, verbose_name=_('City'))

    phone        = models.CharField(max_length=11, verbose_name=_('Phone Number'))
    post_code    = models.CharField(max_length=20, verbose_name=_('Post Code'))
    paid         = models.BooleanField(default=False, verbose_name=_('Is Paid'))

    created = models.DateTimeField(auto_now_add=True, verbose_name=_('Created at'))
    updated = models.DateTimeField(auto_now=True, verbose_name=_('Updated at'))

    class Meta:
        verbose_name        = _('Order')
        verbose_name_plural = _('Orders')
        ordering            = ('-created',)

    def get_total_cost(self) :
        return sum(item.get_cost() for item in self.items.all())

    def __str__(self):
        return f'Order by {self.user} at {self.created}'

class OrderProductItem (models.Model):
    order      = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items', verbose_name=_('Order'))
    product    = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items', verbose_name=_('Product'))
    price      = models.DecimalField(max_digits=10, decimal_places=2, verbose_name=_('Price'))
    quantity   = models.PositiveIntegerField(default=1, verbose_name=_('Quantity'))

    class Meta:
        verbose_name        = _('Order Product')
        verbose_name_plural = _('Order Products')

    def get_cost(self) :
        return self.price * self.quantity

    def __str__(self) :
        return str(self.id)


class OrderFeatureItem (models.Model):
    order_product   = models.ForeignKey(OrderProductItem,
                            on_delete=models.CASCADE,
                            related_name='feature_items',
                            verbose_name=_('Product'))

    feature         = models.ForeignKey(Feature,
                            on_delete=models.CASCADE,
                            related_name='order_features',
                            verbose_name=_('Related Feature'))

    price           = models.DecimalField(max_digits=4,
                            decimal_places=2,
                            verbose_name=_('Feature Price'))

    class Meta:
        verbose_name        = _('Feature Related To Ordering Product')
        verbose_name_plural = _('Features Related To Ordering Products')

    def __str__(self) :
        return str(self.id)

class OrderOptionItem (models.Model):
    order_product = models.ForeignKey(OrderProductItem,
                            on_delete=models.CASCADE,
                            related_name='option_items',
                            verbose_name=_('Product'))

    option        = models.ForeignKey(Option,
                            on_delete=models.CASCADE,
                            related_name='order_options',
                            verbose_name=_('Related Option'))

    price         = models.DecimalField(max_digits=4,
                            decimal_places=2,
                            verbose_name=_('Option Price'))

    class Meta:
        verbose_name        = _('Option Related To Ordering Product')
        verbose_name_plural = _('Options Related To Ordering Products')

    def __str__(self) :
        return str(self.id)

store/views.py
from customUser.models import User
from django import forms
from django.shortcuts import get_object_or_404, redirect, render
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext_lazy as _
from django.core.cache.utils import make_template_fragment_key as mtfk
from django.utils.translation import get_language
from django.conf import settings

from persian_tools import phone_number
from .models import Category, Product, Feature, Option, ProductImage
from BANPars.redis_conf import redis

# For pre-order
from preorder.forms import PreOrderForm
from preorder.models import PreOrder
from django.http import HttpResponseRedirect
from django.contrib import messages



def product_all(request):

    prefix=settings.CACHES['default']['KEY_PREFIX']
    db_number = settings.CACHE_DB_NUMBER

    context = {}
    lang = get_language()
    model_list = [Product, ]

    for model in model_list :

        base_key =  mtfk(f'{model.__name__.lower()}', [lang, ])
        key = f'{prefix}:{db_number}:{base_key}'

        if not redis.exists(key) :
            context[f'{model.__name__.lower()}s'] = model.objects.all()

    return render(request, 'store/home.html', context)

def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/category_products.html', {'category': category, 'products': products})

def product_detail(request, slug):

    # Preorder form submit
    if request.method == 'POST' :
        product = get_object_or_404(Product, slug=slug)
        pre_order = PreOrder(user=request.user, product=product)
        form = PreOrderForm(data=request.POST, instance=pre_order)
        if form.is_valid() :
            form.save()
            messages.success(request, _('Pre-Order was set, we will call you as soon as possible.'))
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else :
            messages.error(request, _('Something went wrong, try again.'))
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    # end

    product = get_object_or_404(Product, slug=slug)
    features = Feature.actives.filter(product=product)
    option_titles = product.titles.all()
    options = {}
    for title in option_titles :
        options[title.name] = title.options.all()

    context = {'product': product, 'features' : features, 'options_details' : options.items()}

    prefix=settings.CACHES['default']['KEY_PREFIX']
    db_number = settings.CACHE_DB_NUMBER
    lang = get_language()
    base_key =  mtfk(f'{ProductImage.__name__.lower()}', [lang, product.pk, ])
    key = f'{prefix}:{db_number}:{base_key}'
    if not redis.exists(key) :
        context['images'] = product.product_image.all()

    # Preorder settings
    form = PreOrderForm(initial={'user':request.user.pk, 'product':product.pk, 'phone_number':request.user.username})
    context['form'] = form
    # end
    return render(request, 'store/single.html', context)

@login_required
def toggle_feature(request, pk) :
    if request.method == 'GET' and request.is_ajax() :
        try :
            price = Feature.actives.get(pk=pk).price
        except :
            return JsonResponse({'error': 'Something went wrong'}, status=400)

        response = JsonResponse({'price':price}, status=200)
        return response

@login_required
def toggle_option(request, pk) :
    if request.method == 'GET' and request.is_ajax() :
        try :
            price = Option.objects.get(pk=pk).price
        except :
            return JsonResponse({'error': 'Something went wrong'}, status=400)

        response = JsonResponse({'price':price}, status=200)
        return response


templates/store/category_products.html
{% extends "base/base.html" %}
{% load static %}
{% load i18n %}


{% block links %}
<link rel="stylesheet" href="{% static 'css/store/products.css' %}">
{% endblock %}


{% block title %}{% if category %}{{ category.name }}{% else %}{% translate 'Products' %}{% endif %}{% endblock %}

{% block content %}

{% include "base/main-navbar.html" %}

{% include 'registration/messages.html' %}


<div class="section product-container">
    <div class="section-title">
        <h2>{% translate 'Related <span>products</span>' %}</h2>
        <h4>{% translate 'Devices you can order' %}</h4>
    </div>

    <!-- presale -->
    <div class="section-center presale-info">
        <p>{% translate '<span>Note:</span> Since we are a young startup and the stock of our products are limited, so for now our policy for selling the products is online-presale.' %}
        </p>
        <p>
            {% translate '<span>How to:</span> All you need to do is to go to product page, press <span class="pre-buy">PRE-BUY</span> button and fill the form. our colleagues will call you as soon as possible.' %}
        </p>
    </div>
    <!-- end of presale -->

    <div class="section-center">

        {% for product in products %}
        <div class="product">
            <div class="product-content">
                <div class="product-img">
                    <img src="{{ product.transparent_image.url }}" alt="Product-image">
                </div>
                <div class="product-btns">
                    <a type="button" class="btn" href="{% url 'store:product_detail' product.slug %}">{% translate 'product details' %} <i class="fas fa-search"></i></a>
                </div>
            </div>
            <div class="product-info">
                <div class="product-info-top">
                    <h2 class="product-name">{{ product.title }}</h2>
                </div>
            </div>
            {% if product.discount_price %}
            <div class="off-info">
                <h2 class="sm-title">{% translate 'off' %}</h2>
            </div>
            {% endif %}
        </div>
        {% endfor %}

    </div>
</div>



{% include 'base/footer.html' %}


{% endblock %}

templates/store/home.html
{% extends "base/base.html" %}
{% load static %}
{% load i18n %}
{% load cache %}
{% get_current_language as LANGUAGE_CODE %}
{% load i18n %}



{% block links %}
<link rel="stylesheet" href="{% static 'css/store/products.css' %}">
{% endblock %}


{% block title %}{% translate 'Store' %}{% endblock %}
{% block content %}

{% include "base/main-navbar.html" %}

{% include 'registration/messages.html' %}


<div class="section product-container">
    <div class="section-title">
        <h2>{% translate 'The <span>products</span>' %}</h2>
        <h4>{% translate 'Devices you can order' %}</h4>
    </div>

    <!-- presale -->
    <div class="section-center presale-info">
        <p>{% translate '<span>Note:</span> Since we are a young startup and the stock of our products are limited, so for now our policy for selling the products is online-presale.' %}
        </p>
        <p>
            {% translate '<span>How to:</span> All you need to do is to go to product page, press <span class="pre-buy">PRE-BUY</span> button and fill the form. our colleagues will call you as soon as possible.' %}
        </p>
    </div>
    <!-- end of presale -->

    <div class="section-center">
        {% cache cache_ttl product LANGUAGE_CODE %}
        {% for product in products %}
        <div class="product">
            <div class="product-content">
                <div class="product-img">
                    <img src="{{ product.transparent_image.url }}" alt="Product-image">
                </div>
                <div class="product-btns">
                    <a type="button" class="btn" href="{% url 'store:product_detail' product.slug %}">{% translate 'product details' %} <i class="fas fa-search"></i></a>
                </div>
            </div>
            <div class="product-info">
                <div class="product-info-top">
                    <h2 class="product-name">{{ product.title }}</h2>
                </div>
            </div>
            {% if product.discount_price %}
            <div class="off-info">
                <h2 class="sm-title">{% translate 'off' %}</h2>
            </div>
            {% endif %}
        </div>
        {% endfor %}
        {% endcache %}

    </div>
</div>



{% include 'base/footer.html' %}


{% endblock %}

templates/store/single.html
{% extends "base/base.html" %}
{% load static %}
{% load i18n %}
{% load cache %}
{% get_current_language as LANGUAGE_CODE %}
{% load widget_tweaks %}
{% load humanize %}


{% block links %}
<link rel="stylesheet" href="{% static 'css/store/product_customization.css' %}">
{% endblock %}


{% block title %}{{ product.title }}{% endblock %}


{% block content %}

{% include 'base/main-navbar.html' %}

{% include 'registration/messages.html' %}




<div class="section product">
    <!-- presale -->
    <div class="section-center presale-info">
        <p>{% translate '<span>Note:</span> Since we are a young startup and the stock of our products are limited, so for now our policy for selling the products is online-presale.' %}
        </p>
        <p>
            {% translate '<span>How to:</span> All you need to do is to go to product page, press <span class="pre-buy">PRE-BUY</span> button and fill the form. our colleagues will call you as soon as possible.' %}
        </p>
    </div>
    <!-- end of presale -->

    <div class="section-center row mt-5">
        {% cache cache_ttl productimage LANGUAGE_CODE product.pk %}
        <div class="col-lg-6 col-md-12 col-12">
            {% with images|first as first %}
                <img src="{{ first.image.url }}" alt="{{ first.alt_text }}" class="img-fluid w-100 pb-1" id="main-image">
            {% endwith %}
            
            <div class="small-img-group product-images">
                {% for image in images %}
                <div class="small-img-col">
                    <img src="{{ image.image.url }}" alt="{{ image.alt_text }}">
                </div>
                {% endfor %}
            </div>
        </div>
        {% endcache %}

        <div class="col-lg-5 col-md-12 col-12 product-details">
            <div class="product-info">
                <h3 class="py-4 product-title">{{ product.title|title }}</h3>
                <div class="product-rating">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star-half-alt"></i>
                    <span>4.7(21)</span>
                </div>
                <h3 class="product-prices">
                    {% if product.discount_price %}
                    <p class="last-price">
                    {% translate 'Old Price :' %} <span>{{ product.price|intcomma }} {% translate 'Toman' %}</span></p>

                    <p class="new-price">
                    {% translate 'New Price :' %} <span id="product-price">{{ product.discount_price|intcomma }} {% translate 'Toman' %}</span></p>
                    {% else %}
                        <p class="new-price">
                        {% translate 'Price :' %} <span id="product-price">{{ product.price|intcomma }} {% translate 'Toman' %}</span></p>
                    {% endif %}
                </h3>
                <div class="product-customizations">
                    <h3>Custmize the item :</h3>
                    <div class="row p-3">
                        <div class="features col-lg-6 col-md-12 col-12">
                            {% for feature in features %}
                            <div class="feature-container">
                                <input type="checkbox" data-index="{{feature.id}}"
                                name="feature" data-price="{{ feature.price }}">
                                <label for="feature">{{feature.name|upper}} ({{feature.price|intcomma}} toman)</label>
                            </div>
                            {% empty %}
                                <p>no feature</p>
                            {% endfor %}
                        </div>
                        <div class="options col-lg-6 col-md-12 col-12">
                            {% for title, options in options_details %}
                            <select name="options" id="option-{{ forloop.counter }}" class="my-3">
                                <option value="None">{{ title|upper }}</option>
                                {% for option in options %}
                                <option value="{{option.id}}" data-price="{{option.price}}">{{option.name|capfirst }} ({{option.price|intcomma}} toman)</option>
                                {% endfor %}
                            </select>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="purchase-info">
                <input type="number" id="quantity" name="quantity" value="1" step="1" min="0">
                <button type="button" class="btn btn-sm" id="add-button" value="{{product.id}}">Add to cart <i class="fas fa-shopping-cart"></i></button>
                <button type="button" class="btn" data-toggle="modal" data-target="#exampleModalCenter">Pre Order <i class="fas fa-phone"></i></button>
            </div>
        </div>
    </div>
    <div class="section-center product-description">
        <div class="p-4">
            <h3 class="py-4">{{ product.title|title }} {% translate 'description:' %}</h3>
            <div class="p-4">
                {{ product.description|safe|title }}
            </div>
        </div>
    </div>
</div>

<!-- Pre-Order Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content"> 
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">{% translate 'Pre Order' %}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post">
                    {% csrf_token %}
                    
                    <div class="form-group">
                        <label class="small font-weight-bold" for="id_fullname">{{ form.fullname.label }}</label>
                        {{ form.fullname|attr:"class:form-control"|attr:"placeholder:Fullname" }}
                    </div>
                    <div class="form-group">
                        <label class="small font-weight-bold" for="id_phone_number">{{ form.phone_number.label }}</label>
                        {{ form.phone_number|attr:"class:form-control"|attr:"placeholder:Phone-number" }}
                    </div>
                    <input type="submit" id="submit-pre-order-form" class="d-none">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn" data-dismiss="modal">{% translate 'Close' %}</button>
                <button type="button" class="btn" id="pre-order-form-btn">{% translate 'Set Pre-order' %}</button>
            </div>
        </div>
    </div>
</div>


{% include 'base/footer.html' %}



{% endblock %}


{% block js-files %}
<script src="{% static 'js/easyHTTP.js' %}"></script>

<script>

    const csrfToken = '{{csrf_token}}';
    const postURL = '{% url "basket:basket_add" %}';
    const getFeatureURL = '{% url "store:feature_price" pk=0 %}';
    const getOptionURL = '{% url "store:option_price" pk=0 %}';
    const addToBasketBtn = document.getElementById('add-button');
    const features = document.getElementsByName('feature');
    const options = document.getElementsByName('options');
    const productPrice = document.getElementById('product-price');
    const qty = document.getElementById('quantity');
    const http = new EasyHTTP;

</script>

<script src="{% static 'js/store/product_customization.js' %}"></script>

<!-- images -->
<script>
    const mainImage = document.getElementById('main-image');
    const smallImages = document.querySelectorAll('.product-images img');
    smallImages.forEach(img => {
        img.addEventListener('click', e => {
            e.preventDefault();
            mainImage.src = img.src;
        })
    })
</script>

<!-- pre-order form submit -->
<script>
    const submit_input = document.getElementById('submit-pre-order-form');
    const submit_btn = document.getElementById('pre-order-form-btn');
    submit_btn.addEventListener('click', e => {
        e.preventDefault();
        submit_input.click();
    })
</script>

{% endblock %}