BANPars/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog
from django.utils.translation import gettext_lazy as _


admin.site.index_title = _('Admin Panel')
admin.site.site_header = _('Company Admin Panel')
admin.site.site_title = _('Company')


urlpatterns = [
    path('lang/', include('lang_ctrl.urls', namespace='lang')),
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('introduction.urls', namespace='introduction')),
    path('shop/', include('store.urls', namespace='store')),
    path('account/', include('accounts.urls', namespace='accounts')),  
    path('basket/', include('basket.urls', namespace='basket')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('addresses/', include('addresses.urls', namespace='addresses')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('preorder/', include('preorder.urls', namespace='preorder')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='js-cat'),
)


addresses/urls.py
from django.urls import path

from . import views

app_name = 'addresses'

urlpatterns = [
    path('cities/', views.get_cities, name='cities'),
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('order/<int:order_id>', views.order, name='order'),
    # path('set_order', views.fill_order, name='set_order'),
    path('product_details/<int:pk>/', views.product_details, name='details'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
    path('feature/<pk>/', views.toggle_feature, name='feature_price'),
    path('option/<pk>/', views.toggle_option, name='option_price'),
]

orders/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from customUser.models import User
from store.models import Product, Feature, Option
from addresses.models import Province, City



class Order (models.Model):
    user         = models.ForeignKey(User, on_delete=models.CASCADE,
                    related_name='orders', verbose_name=_('User'))
    fullname     = models.CharField(max_length=50, verbose_name=_('Fullname'))
    address      = models.TextField(max_length=500, verbose_name=_('Address'))
    delivery_instructions  = models.TextField(max_length=500,
                            verbose_name=_('Delivery instructions'), blank=True, default='')

    province = models.ForeignKey(Province, on_delete=models.PROTECT, verbose_name=_('Province'))
    city         = models.ForeignKey(City, on_delete=models.PROTECT, verbose_name=_('City'))

    phone        = models.CharField(max_length=11, verbose_name=_('Phone Number'))
    post_code    = models.CharField(max_length=20, verbose_name=_('Post Code'))
    paid         = models.BooleanField(default=False, verbose_name=_('Is Paid'))

    created = models.DateTimeField(auto_now_add=True, verbose_name=_('Created at'))
    updated = models.DateTimeField(auto_now=True, verbose_name=_('Updated at'))

    class Meta:
        verbose_name        = _('Order')
        verbose_name_plural = _('Orders')
        ordering            = ('-created',)

    def get_total_cost(self) :
        return sum(item.get_cost() for item in self.items.all())

    def __str__(self):
        return f'Order by {self.user} at {self.created}'

class OrderProductItem (models.Model):
    order      = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items', verbose_name=_('Order'))
    product    = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items', verbose_name=_('Product'))
    price      = models.DecimalField(max_digits=10, decimal_places=2, verbose_name=_('Price'))
    quantity   = models.PositiveIntegerField(default=1, verbose_name=_('Quantity'))

    class Meta:
        verbose_name        = _('Order Product')
        verbose_name_plural = _('Order Products')

    def get_cost(self) :
        return self.price * self.quantity

    def __str__(self) :
        return str(self.id)


class OrderFeatureItem (models.Model):
    order_product   = models.ForeignKey(OrderProductItem,
                            on_delete=models.CASCADE,
                            related_name='feature_items',
                            verbose_name=_('Product'))

    feature         = models.ForeignKey(Feature,
                            on_delete=models.CASCADE,
                            related_name='order_features',
                            verbose_name=_('Related Feature'))

    price           = models.DecimalField(max_digits=4,
                            decimal_places=2,
                            verbose_name=_('Feature Price'))

    class Meta:
        verbose_name        = _('Feature Related To Ordering Product')
        verbose_name_plural = _('Features Related To Ordering Products')

    def __str__(self) :
        return str(self.id)

class OrderOptionItem (models.Model):
    order_product = models.ForeignKey(OrderProductItem,
                            on_delete=models.CASCADE,
                            related_name='option_items',
                            verbose_name=_('Product'))

    option        = models.ForeignKey(Option,
                            on_delete=models.CASCADE,
                            related_name='order_options',
                            verbose_name=_('Related Option'))

    price         = models.DecimalField(max_digits=4,
                            decimal_places=2,
                            verbose_name=_('Option Price'))

    class Meta:
        verbose_name        = _('Option Related To Ordering Product')
        verbose_name_plural = _('Options Related To Ordering Products')

    def __str__(self) :
        return str(self.id)

orders/forms.py
from django import forms
from django.contrib.auth import models
from django.db.models import fields
from django.utils.translation import gettext_lazy as _

from .models import Order
from store.models import Product
from addresses.models import City

from persian_tools import phone_number


class OrderFillForm(forms.ModelForm) :
    # fullname = forms.CharField(label=_('Fullname'), max_length=50)
    # address1 = forms.CharField(label=_('First Address'), max_length=250)
    # address2 = forms.CharField(label=_('Second Address'), max_length=250)
    # description = forms.Textarea(label=_('Description'))
    # province = forms.CharField(label=_('Province'), max_length=50)
    # city = forms.CharField(label=_('City'), max_length=50)
    # phone = forms.CharField(label=_('Phone Number'), max_length=11, help_text='Please provide a valid number in case we needed to cantact you')
    # post_code = forms.CharField(label=_('Post Code'), max_length=20)

    class Meta : 
        model = Order
        fields = ('fullname', 'address', 'delivery_instructions', 'province', 'city', 'phone', 'post_code')

    def clean_address(self) :
        address = self.cleaned_data['address']
        if address == '' :
            raise forms.ValidationError(_('Address can not be blank, Please fill it.'))
        return address

    def clean_province(self) :
        province = self.cleaned_data['province']
        if province == '' :
            raise forms.ValidationError(_('Province can not be blank, Please fill it.'))
        return province

    def clean_city(self) :
        city = self.cleaned_data['city']
        if city == '' :
            raise forms.ValidationError(_('City can not be blank, Please fill it.'))
        return city

    def clean_phone(self) :
        phone = self.cleaned_data['phone']
        if not phone_number.validate(phone) :
            raise forms.ValidationError(_('Phone Number is not correct, Please correct it.'))
        return phone

    def clean_post_code(self) :
        post_code = self.cleaned_data['post_code']
        if post_code == '' or len(post_code) != 10 :
            raise forms.ValidationError(_('Post Code is not correct, Please correct it.'))

    def __init__(self, *args, **kwargs):

        initial = kwargs.get('initial', None)
        if initial  :
            queryset = City.objects.filter(province=initial.get('province') )
        else :
            queryset = City.objects.none()

        super().__init__(*args, **kwargs)
        self.fields['delivery_instructions'].required = False
        self.fields['city'].queryset = queryset


        if 'province' in self.data:
            try:
                province_id = int(self.data.get('province'))
                self.fields['city'].queryset = City.objects.filter(province=province_id)
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.province.city_set.all()




class ProductAddToOrderAdmin(forms.Form) :
    order = forms.ModelChoiceField(queryset=Order.objects.all())
    product = forms.ModelChoiceField(queryset=Product.objects.all())

orders/views.py
from django.forms import fields
from django.shortcuts import redirect, render, get_object_or_404
from django.http import JsonResponse
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Order, OrderProductItem, OrderFeatureItem, OrderOptionItem
from store.models import Product, Feature, Option, OptionCategory

from .forms import OrderFillForm
from basket.basket import Basket

@login_required
def order(request, order_id) :
    order = get_object_or_404(Order, pk=order_id)
    return render(request, 'orders/order.html', {'order' : order})

# @login_required
# def fill_order(request) :
#     basket = Basket(request)
#     if basket.is_empty() :
#         messages.add_message(request, messages.ERROR, 'You have no items in your basket to checkout !!')
#         return redirect('store:product_all')

#     form = OrderFillForm()        
#     if request.method == 'POST' :
#         form = OrderFillForm(request.POST)
#         if form.is_valid() :
#             data = request.POST
#             order = Order.objects.create(user=request.user, fullname=data['fullname'], address1=data['address1'],
#                                 address2=data['address2'], province=data['province'], city=data['city'],
#                                 phone=data['phone'], post_code=data['post_code'])
#             for item in basket :
#                 product = OrderProductItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['qty'])

#                 for feature in item['features'] :
#                     OrderFeatureItem.objects.create(order_product=product, feature=feature, price=feature.price)
#                 for option in item['options'] :
#                     OrderOptionItem.objects.create(order_product=product, option=option, price=option.price)

#             basket.clear()
#             return redirect('orders:order', order.id)

#     return render(request, 'orders/order_fill_form.html', {'form' : form})


## only admin (or anyone that should be able to manipulate orders) must be able to use this function
def product_details(request, pk) :
    if request.method == 'GET' and request.is_ajax() :
        try :
            product = Product.objects.get(pk=pk)
        except :
            return JsonResponse({'error': 'Could not find any result for selected product'}, status=400)
        features = Feature.actives.filter(product=product).order_by('-created')
        data = serializers.serialize('json', list(features), fields=('pk', 'name', 'price'))
        return JsonResponse({'data' : data}, status=200)




templates/orders/order.html
{% extends "base/base.html" %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% block title %}{% translate 'order' %}{% endblock %}


{% block links %}
<link rel="stylesheet" href="{% static 'css/orders/order.css' %}">
{% endblock %}


{% block content %}
{% include "base/nav-main.html" %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card text-center card-form">
                <div class="card-body">
                {% include 'registration/messages.html' %}
                <h3>{% translate 'Checkout:' %}</h3>
                <h2>{% translate 'Total : {{order.get_total_cost}}' %}</h2>
            </div>
        </div>
        </div>
    </div>
</div>

{% endblock %}

templates/orders/order_fill_form.html
{% extends "base/base.html" %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% block title %}{% translate 'order info' %}{% endblock %}


{% block links %}
<link rel="stylesheet" href="{% static 'css/orders/order_fill_form.css' %}">
{% endblock %}

{% block content %}
{% include 'base/main-navbar.html' %}

<div class="section order-container">
    <div class="section-title">
        <h2>{% translate 'The <span>Order</span>' %}</h2>
    </div>

    <div class="section-center container">
        {% if form.errors %}
                {% for field in form %}
                    {% if field.errors %}
                    <div class="alert alert-error" role="alert">
                        {{ field.errors|striptags }}
                    </div>
                    {% endif %}
                {% endfor %}
        {% endif %}

        <div class="row">
            <div class="col-md-12">
                <form method="POST">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label class="small font-weight-bold" for="id_fullname">{% translate 'Fullname' %}</label>
                                    {{ form.fullname|attr:"placeholder:Fullname"|attr:"class:form-control mb-3" }}
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="small font-weight-bold" for="id_phone">{% translate 'Phone number' %}</label>
                                    {{ form.phone|attr:"placeholder:Phone number"|attr:"class:form-control mb-3" }}
                                </div>
                            </div>
                
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label class="small font-weight-bold" for="id_province">{% translate 'Province' %}</label>
                                    {{ form.province|attr:"placeholder:Province"|attr:"class:form-control mb-3" }}
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="small font-weight-bold" for="id_city">{% translate 'City' %}</label>
                                    {{ form.city|attr:"placeholder:City"|attr:"class:form-control mb-3" }}
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="small font-weight-bold" for="id_post_code">{% translate 'Post code' %}</label>
                                {{ form.post_code|attr:"placeholder:Post code"|attr:"class:form-control mb-3" }}
                            </div>
                        </div>

                        <div class="col-md-7">
                            <div class="form-group">
                                <label class="small font-weight-bold">{{ form.address.label}}
                                    </label>
                                {{ form.address|attr:"placeholder:Address"|attr:"class:form-control"|attr:"rows:5" }}
                            </div>
        
                            <div class="form-group">
                                <label class="small font-weight-bold">{{ form.delivery_instructions.label}}</label>
                                {{ form.delivery_instructions|attr:"placeholder:Delivery Instructions"|attr:"class:form-control"|attr:'rows:5' }}
                                <small id="id_delivery_instructions" class="form-text text-muted">{% translate 'Tell us any other points you find nessecery about your order' %}
                                </small>
                            </div>
                        </div>
                    </div>
        
                    <div class="order-submit">
                        <input type="submit" value="{% translate 'Submit' %}" class="btn">
                    </div>
        
                </form>
            </div>
        </div>


    </div>
</div>



{% include 'base/footer.html' %}


{% endblock %}

{% block js-files %}
<script src="{% static 'js/easyHTTP.js' %}"></script>

<script>
    const csrfToken = '{{csrf_token}}';
    const http = new EasyHTTP;
</script>


<script>
    const province = document.getElementById('id_province');
    const cities_url = '{% url "addresses:cities" %}';
    const city_section = document.getElementById('id_city');


    province.addEventListener('change', e => {

        if(province.options[province.selectedIndex].value === ''){
            inner = '<option value="">---------</option>';
            city_section.innerHTML = inner;
            return;
        }

        let url = cities_url.concat(`?province=${province.options[province.selectedIndex].value}`);

        http.get(url, function(err, res){
            if(!err){
                let inner;
                response = JSON.parse(JSON.parse(res)['cities']);
                inner = '<option value="">---------</option>';

                response.forEach(city => {
                    inner += `<option value="${city.pk}"> ${city.fields.city} </option>`
                })

                city_section.innerHTML = inner;
            } else {
                console.log(err);
            }
        })
    })

</script>
{% endblock %}